name: Say Hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Display a Welcome Message
        run: echo "Hola Josue Barrera!"

      - name: Show Current Date and Time
        run: date
        
      - name: List Directory Contents
        run: ls -l
